//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SupperClub.Domain
{
    public partial class aspnet_Users
    {
        #region Primitive Properties
    
        public virtual System.Guid ApplicationId
        {
            get;
            set;
        }
    
        public virtual System.Guid UserId
        {
            get;
            set;
        }
    
        public virtual string UserName
        {
            get;
            set;
        }
    
        public virtual string LoweredUserName
        {
            get;
            set;
        }
    
        public virtual string MobileAlias
        {
            get;
            set;
        }
    
        public virtual bool IsAnonymous
        {
            get;
            set;
        }
    
        public virtual System.DateTime LastActivityDate
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties

        public virtual aspnet_Membership aspnet_Membership { get; set; }

        public virtual User User { get; set; }

        #endregion
        
    }
}
