//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace SupperClub.Domain 
{
    public class BookingCancellationLog
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int EventId
        {
            get;
            set;
        }        
    
        public virtual System.Guid UserId
        {
            get;
            set;
        }
        public virtual System.Guid AdminUserId
        {
            get;
            set;
        }
        public int SeatingId { get; set; }        

        public int MenuOptionId { get; set; }

        public int VoucherId { get; set; }
       
        public virtual Nullable<decimal> TotalBasePrice
        {
            get;
            set;
        }

        public virtual Nullable<decimal> TotalPrice
        {
            get;
            set;
        }
        public virtual Nullable<decimal> HostNetPrice
        {
            get;
            set;
        }
        public virtual Nullable<decimal> GuestBasePrice
        {
            get;
            set;
        }
        public virtual Nullable<decimal> Discount
        {
            get;
            set;
        }
        
        public virtual Nullable<DateTime> BookingDateTime
        {
            get;
            set;
        }
        public virtual DateTime CancelDateTime
        {
            get;
            set;
        }
        public int BookingReference { get; set; }
        public virtual int NumberOfGuests
        {
            get;
            set;
        }
        #endregion

       
    }
}
