//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SupperClub.Domain
{
    public class EventDiet
    {
        #region Primitive Properties

        public virtual int Id
        {
            get;
            set;
        }

        public virtual int EventId
        {
            get { return _eventId; }
            set
            {
                if (_eventId != value)
                {
                    if (Event != null && Event.Id != value)
                    {
                        Event = null;
                    }
                    _eventId = value;
                }
            }
        }
        private int _eventId;

        public virtual int DietId
        {
            get { return _dietId; }
            set
            {
                if (_dietId != value)
                {
                    if (Diet != null && Diet.Id != value)
                    {
                        Diet = null;
                    }
                    _dietId = value;
                }
            }
        }
        private int _dietId;

        #endregion
        #region Navigation Properties

        public virtual Diet Diet
        {
            get { return _diet; }
            set
            {
                if (!ReferenceEquals(_diet, value))
                {
                    var previousValue = _diet;
                    _diet = value;
                    FixupDiet(previousValue);
                }
            }
        }
        private Diet _diet;

        public virtual Event Event
        {
            get { return _event; }
            set
            {
                if (!ReferenceEquals(_event, value))
                {
                    var previousValue = _event;
                    _event = value;
                    FixupEvent(previousValue);
                }
            }
        }
        private Event _event;

        #endregion
        #region Association Fixup

        private void FixupDiet(Diet previousValue)
        {
            if (previousValue != null && previousValue.EventDiets.Contains(this))
            {
                previousValue.EventDiets.Remove(this);
            }

            if (Diet != null)
            {
                if (!Diet.EventDiets.Contains(this))
                {
                    Diet.EventDiets.Add(this);
                }
                if (DietId != Diet.Id)
                {
                    DietId = Diet.Id;
                }
            }
        }

        private void FixupEvent(Event previousValue)
        {
            if (previousValue != null && previousValue.EventDiets.Contains(this))
            {
                previousValue.EventDiets.Remove(this);
            }

            if (Event != null)
            {
                if (!Event.EventDiets.Contains(this))
                {
                    Event.EventDiets.Add(this);
                }
                if (EventId != Event.Id)
                {
                    EventId = Event.Id;
                }
            }
        }

        #endregion
    }
}
