//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SupperClub.Domain
{
    public class EventRecommendation
    {
        #region Primitive Properties

        public virtual int Id
        {
            get;
            set;
        }

        public virtual int EventId
        {
            get { return _eventId; }
            set
            {
                if (_eventId != value)
                {
                    if (Event != null && Event.Id != value)
                    {
                        Event = null;
                    }
                    _eventId = value;
                }
            }
        }
        private int _eventId;

        public virtual int RecommendedEventId
        {
            get { return _recommendedEventId; }
            set
            {
                if (_recommendedEventId != value)
                {
                    if (RecommendedEvent != null && RecommendedEvent.Id != value)
                    {
                        RecommendedEvent = null;
                    }
                    _recommendedEventId = value;
                }
            }
        }
        private int _recommendedEventId;

        #endregion
        #region Navigation Properties

        public virtual Event RecommendedEvent
        {
            get { return _recommendedEvent; }
            set
            {
                if (!ReferenceEquals(_recommendedEvent, value))
                {
                    var previousValue = _recommendedEvent;
                    _recommendedEvent = value;
                    FixupRecommendedEvent(previousValue);
                }
            }
        }
        private Event _recommendedEvent;

        public virtual Event Event
        {
            get { return _event; }
            set
            {
                if (!ReferenceEquals(_event, value))
                {
                    var previousValue = _event;
                    _event = value;
                    FixupEvent(previousValue);
                }
            }
        }
        private Event _event;

        #endregion
        #region Association Fixup

        private void FixupRecommendedEvent(Event previousValue)
        {
            if (previousValue != null && previousValue.EventRecommendations.Contains(this))
            {
                previousValue.EventRecommendations.Remove(this);
            }

            if (RecommendedEvent != null)
            {
                if (!RecommendedEvent.EventRecommendations.Contains(this))
                {
                    RecommendedEvent.EventRecommendations.Add(this);
                }
                if (RecommendedEventId != RecommendedEvent.Id)
                {
                    RecommendedEventId = RecommendedEvent.Id;
                }
            }
        }

        private void FixupEvent(Event previousValue)
        {
            if (previousValue != null && previousValue.EventRecommendations.Contains(this))
            {
                previousValue.EventRecommendations.Remove(this);
            }

            if (Event != null)
            {
                if (!Event.EventRecommendations.Contains(this))
                {
                    Event.EventRecommendations.Add(this);
                }
                if (EventId != Event.Id)
                {
                    EventId = Event.Id;
                }
            }
        }

        #endregion
    }
}
