//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SupperClub.Domain
{
    public class EventMenuOption
    {
        #region Primitive Properties

        public virtual int Id
        {
            get;
            set;
        }

        public virtual int EventId
        {
            get { return _eventId; }
            set
            {
                if (_eventId != value)
                {
                    if (Event != null && Event.Id != value)
                    {
                        Event = null;
                    }
                    _eventId = value;
                }
            }
        }
        private int _eventId;

        public virtual string Title
        {
            get;
            set;
        }

        public virtual string Description
        {
            get;
            set;
        }
        public virtual decimal Cost
        {
            get;
            set;
        }
        public virtual bool IsDefault
        {
            get;
            set;
        }
        public virtual DateTime DateCreated
        {
            get;
            set;
        }
        //public virtual bool MinMaxBookingEnabled
        //{
        //    get;
        //    set;
        //}
        //public virtual bool SeatSelectionInMultipleOfMin
        //{
        //    get;
        //    set;
        //}
        //public virtual int MinTicketsAllowed
        //{
        //    get;
        //    set;
        //}
        //public virtual int MaxTicketsAllowed
        //{
        //    get;
        //    set;
        //}
        /// <summary>
        /// Gets cost to guest
        /// </summary>
        public decimal CostToGuest
        {
            get
            {
                return CostCalculator.CostToGuest(this.Cost, this.Event.Commission);
            }
        }
        public virtual List<EventAttendee> EventAttendees { get; set; }
        #endregion
        #region Navigation Properties

        public virtual Event Event
        {
            get { return _event; }
            set
            {
                if (!ReferenceEquals(_event, value))
                {
                    var previousValue = _event;
                    _event = value;
                    FixupEvent(previousValue);
                }
            }
        }
        private Event _event;

        //public virtual ICollection<EventAttendee> EventAttendees
        //{
        //    get
        //    {
        //        if (_eventAttendees == null)
        //        {
        //            var newCollection = new FixupCollection<EventAttendee>();
        //            newCollection.CollectionChanged += FixupEventAttendees;
        //            _eventAttendees = newCollection;
        //        }
        //        return _eventAttendees;
        //    }
        //    set
        //    {
        //        if (!ReferenceEquals(_eventAttendees, value))
        //        {
        //            var previousValue = _eventAttendees as FixupCollection<EventAttendee>;
        //            if (previousValue != null)
        //            {
        //                previousValue.CollectionChanged -= FixupEventAttendees;
        //            }
        //            _eventAttendees = value;
        //            var newValue = value as FixupCollection<EventAttendee>;
        //            if (newValue != null)
        //            {
        //                newValue.CollectionChanged += FixupEventAttendees;
        //            }
        //        }
        //    }
        //}
        //private ICollection<EventAttendee> _eventAttendees;
        #endregion
        #region Association Fixup

        private void FixupEvent(Event previousValue)
        {
            if (previousValue != null && previousValue.EventMenuOptions.Contains(this))
            {
                previousValue.EventMenuOptions.Remove(this);
            }

            if (Event != null)
            {
                if (!Event.EventMenuOptions.Contains(this))
                {
                    Event.EventMenuOptions.Add(this);
                }
                if (EventId != Event.Id)
                {
                    EventId = Event.Id;
                }
            }
        }
        //private void FixupEventAttendees(object sender, NotifyCollectionChangedEventArgs e)
        //{
        //    if (e.NewItems != null)
        //    {
        //        foreach (EventAttendee item in e.NewItems)
        //        {
        //            item.EventMenuOption = this;
        //        }
        //    }

        //    if (e.OldItems != null)
        //    {
        //        foreach (EventAttendee item in e.OldItems)
        //        {
        //            if (ReferenceEquals(item.EventMenuOption, this))
        //            {
        //                item.EventMenuOption = null;
        //            }
        //        }
        //    }
        //}
        #endregion
    }
}
