//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SupperClub.Domain
{
    public class EventVoucher
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int EventId
        {
            get { return _eventId; }
            set
            {
                if (_eventId != value)
                {
                    if (Event != null && Event.Id != value)
                    {
                        Event = null;
                    }
                    _eventId = value;
                }
            }
        }
        private int _eventId;
    
        public virtual int VoucherId
        {
            get { return _voucherId; }
            set
            {
                if (_voucherId != value)
                {
                    if (Voucher != null && Voucher.Id != value)
                    {
                        Voucher = null;
                    }
                    _voucherId = value;
                }
            }
        }
        private int _voucherId;

        #endregion
        #region Navigation Properties
    
        public virtual Voucher Voucher
        {
            get { return _voucher; }
            set
            {
                if (!ReferenceEquals(_voucher, value))
                {
                    var previousValue = _voucher;
                    _voucher = value;
                    FixupVoucher(previousValue);
                }
            }
        }
        private Voucher _voucher;
    
        public virtual Event Event
        {
            get { return _event; }
            set
            {
                if (!ReferenceEquals(_event, value))
                {
                    var previousValue = _event;
                    _event = value;
                    FixupEvent(previousValue);
                }
            }
        }
        private Event _event;

        #endregion
        #region Association Fixup
    
        private void FixupVoucher(Voucher previousValue)
        {
            if (previousValue != null && previousValue.EventVouchers.Contains(this))
            {
                previousValue.EventVouchers.Remove(this);
            }
    
            if (Voucher != null)
            {
                if (!Voucher.EventVouchers.Contains(this))
                {
                    Voucher.EventVouchers.Add(this);
                }
                if (VoucherId != Voucher.Id)
                {
                    VoucherId = Voucher.Id;
                }
            }
        }
    
        private void FixupEvent(Event previousValue)
        {
            if (previousValue != null && previousValue.EventVouchers.Contains(this))
            {
                previousValue.EventVouchers.Remove(this);
            }
    
            if (Event != null)
            {
                if (!Event.EventVouchers.Contains(this))
                {
                    Event.EventVouchers.Add(this);
                }
                if (EventId != Event.Id)
                {
                    EventId = Event.Id;
                }
            }
        }

        #endregion
    }
}
