//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SupperClub.Domain
{
    public class EventPriceChangeLog
    {
        #region Primitive Properties

        public virtual int ID
        {
            get;
            set;
        }

        public virtual System.DateTime Date
        {
            get;
            set;
        }

        
        public virtual decimal OldPrice
        {
            get;
            set;
        }

        public virtual decimal NewPrice
        {
            get;
            set;
        }

        public virtual int MenuOptionId
        {
            get;
            set;
        }

        public virtual int EventId
        {
            get;
            set;
        }
        public virtual Guid UserId
        {
            get;
            set;
        }

        #endregion
    }
}
