//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SupperClub.Domain
{
    public class EventArea
    {
        #region Primitive Properties

        public virtual int Id
        {
            get;
            set;
        }

        public virtual int EventId
        {
            get { return _eventId; }
            set
            {
                if (_eventId != value)
                {
                    if (Event != null && Event.Id != value)
                    {
                        Event = null;
                    }
                    _eventId = value;
                }
            }
        }
        private int _eventId;

        public virtual int AreaId
        {
            get { return _areaId; }
            set
            {
                if (_areaId != value)
                {
                    if (Area != null && Area.Id != value)
                    {
                        Area = null;
                    }
                    _areaId = value;
                }
            }
        }
        private int _areaId;

        #endregion
        #region Navigation Properties

        public virtual Area Area
        {
            get { return _area; }
            set
            {
                if (!ReferenceEquals(_area, value))
                {
                    var previousValue = _area;
                    _area = value;
                    FixupArea(previousValue);
                }
            }
        }
        private Area _area;

        public virtual Event Event
        {
            get { return _event; }
            set
            {
                if (!ReferenceEquals(_event, value))
                {
                    var previousValue = _event;
                    _event = value;
                    FixupEvent(previousValue);
                }
            }
        }
        private Event _event;

        #endregion
        #region Association Fixup

        private void FixupArea(Area previousValue)
        {
            if (previousValue != null && previousValue.EventAreas.Contains(this))
            {
                previousValue.EventAreas.Remove(this);
            }

            if (Area != null)
            {
                if (!Area.EventAreas.Contains(this))
                {
                    Area.EventAreas.Add(this);
                }
                if (AreaId != Area.Id)
                {
                    AreaId = Area.Id;
                }
            }
        }

        private void FixupEvent(Event previousValue)
        {
            if (previousValue != null && previousValue.EventAreas.Contains(this))
            {
                previousValue.EventAreas.Remove(this);
            }

            if (Event != null)
            {
                if (!Event.EventAreas.Contains(this))
                {
                    Event.EventAreas.Add(this);
                }
                if (EventId != Event.Id)
                {
                    EventId = Event.Id;
                }
            }
        }

        #endregion
    }
}
