//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace SupperClub.Domain
{
    public class PriceRange  
    {
        #region Primitive Properties
        public virtual int Id
        {
            get;
            set;
        }

        [Display(Name = "Price Name")]
        public virtual string PriceName
        {
            get;
            set;
        }
        [Display(Name = "Min Price")]
        public virtual decimal MinPrice
        {
            get;
            set;
        }
        [Display(Name = "Max Price")]
        public virtual decimal MaxPrice
        {
            get;
            set;
        }

        [Display(Name = "Country")]
        public virtual string Country
        {
            get;
            set;
        }
        #endregion

    }
}