//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations.Schema;

namespace SupperClub.Domain
{
    public class SearchCategoryTag
    {
        #region Primitive Properties

        public virtual int TagId
        {
            get;
            set;
        }
        public virtual int SearchCategoryId
        {
            get;
            set;
        }
        [ForeignKey("TagId")]
        public virtual Tag Tag { get; set; }

        [ForeignKey("SearchCategoryId")]
        public virtual SearchCategory SearchCategory { get; set; }
        #endregion
        
      
    }
}
