//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SupperClub.Domain
{
    public class SupperClubImage
    {
        #region Primitive Properties

        public virtual int Id
        {
            get;
            set;
        }

        public virtual int SupperClubId
        {
            get { return _supperClubId; }
            set
            {
                if (_supperClubId != value)
                {
                    if (SupperClub != null && SupperClub.Id != value)
                    {
                        SupperClub = null;
                    }
                    _supperClubId = value;
                }
            }
        }
        private int _supperClubId;

        public virtual string ImagePath
        {
            get;
            set;
        }        

        #endregion
        #region Navigation Properties

        public virtual SupperClub SupperClub
        {
            get { return _supperClub; }
            set
            {
                if (!ReferenceEquals(_supperClub, value))
                {
                    var previousValue = _supperClub;
                    _supperClub = value;
                    FixupSupperClub(previousValue);
                }
            }
        }
        private SupperClub _supperClub;

        #endregion
        #region Association Fixup

        private void FixupSupperClub(SupperClub previousValue)
        {
            if (previousValue != null && previousValue.SupperClubImages.Contains(this))
            {
                previousValue.SupperClubImages.Remove(this);
            }

            if (SupperClub != null)
            {
                if (!SupperClub.SupperClubImages.Contains(this))
                {
                    SupperClub.SupperClubImages.Add(this);
                }
                if (SupperClubId != SupperClub.Id)
                {
                    SupperClubId = SupperClub.Id;
                }
            }
        }

        #endregion
    }
}
