//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SupperClub.Domain
{
    public class SupperClubVoucher
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int SupperClubId
        {
            get { return _supperClubId; }
            set
            {
                if (_supperClubId != value)
                {
                    if (SupperClub != null && SupperClub.Id != value)
                    {
                        SupperClub = null;
                    }
                    _supperClubId = value;
                }
            }
        }
        private int _supperClubId;
    
        public virtual int VoucherId
        {
            get { return _voucherId; }
            set
            {
                if (_voucherId != value)
                {
                    if (Voucher != null && Voucher.Id != value)
                    {
                        Voucher = null;
                    }
                    _voucherId = value;
                }
            }
        }
        private int _voucherId;

        #endregion
        #region Navigation Properties
    
        public virtual Voucher Voucher
        {
            get { return _voucher; }
            set
            {
                if (!ReferenceEquals(_voucher, value))
                {
                    var previousValue = _voucher;
                    _voucher = value;
                    FixupVoucher(previousValue);
                }
            }
        }
        private Voucher _voucher;
    
        public virtual SupperClub SupperClub
        {
            get { return _supperClub; }
            set
            {
                if (!ReferenceEquals(_supperClub, value))
                {
                    var previousValue = _supperClub;
                    _supperClub = value;
                    FixupSupperClub(previousValue);
                }
            }
        }
        private SupperClub _supperClub;

        #endregion
        #region Association Fixup
    
        private void FixupVoucher(Voucher previousValue)
        {
            if (previousValue != null && previousValue.SupperClubVouchers.Contains(this))
            {
                previousValue.SupperClubVouchers.Remove(this);
            }
    
            if (Voucher != null)
            {
                if (!Voucher.SupperClubVouchers.Contains(this))
                {
                    Voucher.SupperClubVouchers.Add(this);
                }
                if (VoucherId != Voucher.Id)
                {
                    VoucherId = Voucher.Id;
                }
            }
        }
    
        private void FixupSupperClub(SupperClub previousValue)
        {
            if (previousValue != null && previousValue.SupperClubVouchers.Contains(this))
            {
                previousValue.SupperClubVouchers.Remove(this);
            }
    
            if (SupperClub != null)
            {
                if (!SupperClub.SupperClubVouchers.Contains(this))
                {
                    SupperClub.SupperClubVouchers.Add(this);
                }
                if (SupperClubId != SupperClub.Id)
                {
                    SupperClubId = SupperClub.Id;
                }
            }
        }

        #endregion
    }
}
