//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SupperClub.Domain
{
    public class UsageEventType
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual string Description
        {
            get;
            set;
        }
    
        public virtual string Note
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<UserUsageStatistic> UserUsageStatistics
        {
            get
            {
                if (_userUsageStatistics == null)
                {
                    var newCollection = new FixupCollection<UserUsageStatistic>();
                    newCollection.CollectionChanged += FixupUserUsageStatistics;
                    _userUsageStatistics = newCollection;
                }
                return _userUsageStatistics;
            }
            set
            {
                if (!ReferenceEquals(_userUsageStatistics, value))
                {
                    var previousValue = _userUsageStatistics as FixupCollection<UserUsageStatistic>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupUserUsageStatistics;
                    }
                    _userUsageStatistics = value;
                    var newValue = value as FixupCollection<UserUsageStatistic>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupUserUsageStatistics;
                    }
                }
            }
        }
        private ICollection<UserUsageStatistic> _userUsageStatistics;

        #endregion

        #region Association Fixup
    
        private void FixupUserUsageStatistics(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (UserUsageStatistic item in e.NewItems)
                {
                    item.UsageEventType1 = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (UserUsageStatistic item in e.OldItems)
                {
                    if (ReferenceEquals(item.UsageEventType1, this))
                    {
                        item.UsageEventType1 = null;
                    }
                }
            }
        }

        #endregion
    }
}
