//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SupperClub.Domain
{
    public class UserUsageStatistic
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual System.Guid UserId
        {
            get { return _userId; }
            set
            {
                if (_userId != value)
                {
                    if (User != null && User.Id != value)
                    {
                        User = null;
                    }
                    _userId = value;
                }
            }
        }
        private System.Guid _userId;
    
        public virtual int UsageEventType
        {
            get { return _usageEventType; }
            set
            {
                if (_usageEventType != value)
                {
                    if (UsageEventType1 != null && UsageEventType1.ID != value)
                    {
                        UsageEventType1 = null;
                    }
                    _usageEventType = value;
                }
            }
        }
        private int _usageEventType;
    
        public virtual System.DateTime UsageEventTime
        {
            get;
            set;
        }
    
        public virtual string Note
        {
            get;
            set;
        }
    
        public virtual bool IsMobileEvent
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual UsageEventType UsageEventType1
        {
            get { return _usageEventType1; }
            set
            {
                if (!ReferenceEquals(_usageEventType1, value))
                {
                    var previousValue = _usageEventType1;
                    _usageEventType1 = value;
                    FixupUsageEventType1(previousValue);
                }
            }
        }
        private UsageEventType _usageEventType1;
    
        public virtual User User
        {
            get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    var previousValue = _user;
                    _user = value;
                    FixupUser(previousValue);
                }
            }
        }
        private User _user;

        #endregion
        #region Association Fixup
    
        private void FixupUsageEventType1(UsageEventType previousValue)
        {
            if (previousValue != null && previousValue.UserUsageStatistics.Contains(this))
            {
                previousValue.UserUsageStatistics.Remove(this);
            }
    
            if (UsageEventType1 != null)
            {
                if (!UsageEventType1.UserUsageStatistics.Contains(this))
                {
                    UsageEventType1.UserUsageStatistics.Add(this);
                }
                if (UsageEventType != UsageEventType1.ID)
                {
                    UsageEventType = UsageEventType1.ID;
                }
            }
        }
    
        private void FixupUser(User previousValue)
        {
            if (previousValue != null && previousValue.UserUsageStatistics.Contains(this))
            {
                previousValue.UserUsageStatistics.Remove(this);
            }
    
            if (User != null)
            {
                if (!User.UserUsageStatistics.Contains(this))
                {
                    User.UserUsageStatistics.Add(this);
                }
                if (UserId != User.Id)
                {
                    UserId = User.Id;
                }
            }
        }

        #endregion
    }
}
